import type { ReactNode } from 'react'
import {
  CursorArrowRaysIcon, CursorArrowRippleIcon, PlusCircleIcon, ClipboardDocumentIcon,
  PencilSquareIcon, PencilIcon, Bars3BottomLeftIcon, ChevronUpDownIcon, MagnifyingGlassIcon,
  AdjustmentsHorizontalIcon, CheckCircleIcon, QueueListIcon, PowerIcon, CalculatorIcon,
  ViewColumnsIcon, ArrowUpTrayIcon, HashtagIcon, KeyIcon, MagnifyingGlassCircleIcon,
  ListBulletIcon, SwatchIcon, CalendarDaysIcon, CalendarIcon,
  TagIcon, FunnelIcon, UserCircleIcon, UsersIcon, SignalIcon, CommandLineIcon,
  ChartBarIcon, StarIcon, FolderIcon, PresentationChartLineIcon, ArrowTrendingUpIcon, CodeBracketIcon,
  ExclamationTriangleIcon, MegaphoneIcon, ChartPieIcon, ArrowPathIcon, RectangleStackIcon, BellAlertIcon, CheckBadgeIcon,
  Square2StackIcon, ChevronRightIcon, EllipsisHorizontalCircleIcon, ArrowLongRightIcon, ClockIcon, WindowIcon, Bars3Icon,
  RectangleGroupIcon, ArrowsRightLeftIcon, ChatBubbleBottomCenterTextIcon, ChatBubbleLeftEllipsisIcon, EllipsisVerticalIcon, ChevronDownIcon, BellIcon,
  MinusIcon, CreditCardIcon, InboxIcon, TableCellsIcon, PhotoIcon,
} from '@heroicons/react/24/outline'

// Per-component glyph for the sidebar submenu items. One Heroicon per slug.
export const COMP_ICON: Record<string, ReactNode> = {
  // Acciones
  'button': <CursorArrowRaysIcon />,
  'icon-button': <CursorArrowRippleIcon />,
  'fab': <PlusCircleIcon />,
  'copy-button': <ClipboardDocumentIcon />,
  // Inputs
  'field': <PencilSquareIcon />,
  'textarea': <Bars3BottomLeftIcon />,
  'select': <ChevronUpDownIcon />,
  'search-input': <MagnifyingGlassIcon />,
  'slider': <AdjustmentsHorizontalIcon />,
  'checkbox': <CheckCircleIcon />,
  'radio-group': <QueueListIcon />,
  'toggle': <PowerIcon />,
  'quantity-stepper': <CalculatorIcon />,
  'segmented-control': <ViewColumnsIcon />,
  'file-dropzone': <ArrowUpTrayIcon />,
  'number-input': <HashtagIcon />,
  'pin-input': <KeyIcon />,
  'combobox': <MagnifyingGlassCircleIcon />,
  'multi-select': <ListBulletIcon />,
  'color-picker': <SwatchIcon />,
  'editable': <PencilIcon />,
  'calendar': <CalendarDaysIcon />,
  'date-picker': <CalendarIcon />,
  'date-range': <CalendarDaysIcon />,
  // Datos
  'badge': <TagIcon />,
  'chip': <FunnelIcon />,
  'tag': <TagIcon />,
  'avatar': <UserCircleIcon />,
  'avatar-group': <UsersIcon />,
  'status-dot': <SignalIcon />,
  'kbd': <CommandLineIcon />,
  'stat-tile': <ChartBarIcon />,
  'description-list': <ListBulletIcon />,
  'rating': <StarIcon />,
  'tree': <FolderIcon />,
  'virtual-list': <QueueListIcon />,
  'sparkline': <PresentationChartLineIcon />,
  'statistic': <ArrowTrendingUpIcon />,
  'code': <CodeBracketIcon />,
  // Feedback
  'alert': <ExclamationTriangleIcon />,
  'banner': <MegaphoneIcon />,
  'progress': <ChartBarIcon />,
  'progress-ring': <ChartPieIcon />,
  'spinner': <ArrowPathIcon />,
  'skeleton': <RectangleStackIcon />,
  'toast': <BellAlertIcon />,
  'result': <CheckBadgeIcon />,
  // Navegación
  'tabs': <Square2StackIcon />,
  'breadcrumb': <ChevronRightIcon />,
  'pagination': <EllipsisHorizontalCircleIcon />,
  'stepper': <ArrowLongRightIcon />,
  'timeline': <ClockIcon />,
  'nav-sidebar': <ViewColumnsIcon />,
  'sidebar': <Bars3BottomLeftIcon />,
  'topbar': <WindowIcon />,
  'nav-menu': <Bars3Icon />,
  // Overlays
  'modal': <RectangleGroupIcon />,
  'drawer': <ArrowsRightLeftIcon />,
  'tooltip': <ChatBubbleBottomCenterTextIcon />,
  'popover': <ChatBubbleLeftEllipsisIcon />,
  'menu': <EllipsisVerticalIcon />,
  'dropdown': <ChevronDownIcon />,
  'context-menu': <CursorArrowRaysIcon />,
  'user-menu': <UserCircleIcon />,
  'command-palette': <CommandLineIcon />,
  'notifications': <BellIcon />,
  // Layout
  'stack': <RectangleStackIcon />,
  'divider': <MinusIcon />,
  'card': <CreditCardIcon />,
  'empty-state': <InboxIcon />,
  'accordion': <ChevronUpDownIcon />,
  'collapsible': <ChevronDownIcon />,
  'table': <TableCellsIcon />,
  'carousel': <PhotoIcon />,
  'splitter': <ViewColumnsIcon />,
}
